-- MySQL Script generated by MySQL Workbench
-- Wed Oct 29 23:05:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventario` DEFAULT CHARACTER SET utf8mb3 ;
USE `inventario` ;

-- -----------------------------------------------------
-- Table `inventario`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `codigo_producto` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(200) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `foto` LONGBLOB NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NULL DEFAULT NULL,
  `stock` INT NULL DEFAULT NULL,
  `stock_minimo` INT NULL DEFAULT '5',
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventario`.`ajuste_inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`ajuste_inventario` (
  `id_ajuste` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `motivo` TEXT NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_ajuste`),
  INDEX `fk_ajuste_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_ajuste_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `inventario`.`producto` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventario`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL DEFAULT NULL,
  `direccion` VARCHAR(150) NULL DEFAULT NULL,
  `telefono_fijo` VARCHAR(20) NULL DEFAULT NULL,
  `celular` VARCHAR(20) NULL DEFAULT NULL,
  `nota` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventario`.`entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`entrada` (
  `id_entrada` INT NOT NULL AUTO_INCREMENT,
  `id_proveedor` INT NOT NULL,
  `fecha_hora` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `nota` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_entrada`),
  INDEX `fk_entrada_proveedor_idx` (`id_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_entrada_proveedor`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `inventario`.`proveedor` (`id_proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventario`.`detalle_entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`detalle_entrada` (
  `id_detalleentrada` INT NOT NULL AUTO_INCREMENT,
  `id_entrada` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `nota` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_detalleentrada`),
  INDEX `fk_detalle_entrada_entrada1_idx` (`id_entrada` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_entrada_entrada1`
    FOREIGN KEY (`id_entrada`)
    REFERENCES `inventario`.`entrada` (`id_entrada`),
  CONSTRAINT `fk_detalle_entrada_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `inventario`.`producto` (`id_producto`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventario`.`salida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`salida` (
  `id_salida` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `nota` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_salida`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventario`.`detalle_salida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`detalle_salida` (
  `id_detallesalida` INT NOT NULL AUTO_INCREMENT,
  `id_salida` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `nota` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_detallesalida`),
  INDEX `fk_detalle_salida_salida1_idx` (`id_salida` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_salida_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `inventario`.`producto` (`id_producto`),
  CONSTRAINT `fk_detalle_salida_salida1`
    FOREIGN KEY (`id_salida`)
    REFERENCES `inventario`.`salida` (`id_salida`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventario`.`historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`historial` (
  `id_historial` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `tipo_movimiento` ENUM('ENTRADA', 'SALIDA') NOT NULL,
  `cantidad` INT NOT NULL,
  `fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario` VARCHAR(50) NULL DEFAULT NULL,
  `nota` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_historial`),
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `historial_ibfk_1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `inventario`.`producto` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventario`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventario`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `id_rol` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  INDEX `fk_usuario_rol` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `inventario`.`rol` (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `inventario`.`recuperacion_password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`recuperacion_password` (
  `id_recuperacion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `token` VARCHAR(100) NOT NULL,
  `fecha_solicitud` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` ENUM('PENDIENTE', 'COMPLETADO') NULL DEFAULT 'PENDIENTE',
  PRIMARY KEY (`id_recuperacion`),
  INDEX `fk_recuperacion_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_recuperacion_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `inventario`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
